 name: install apt packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - curl
    - build-essential

- name: install ARMHF-compatible nodejs
  apt: deb=http://node-arm.herokuapp.com/node_latest_armhf.deb

- name: install node-RED
  npm: name="{{ item }}" global=yes state=present
  with_items:
    - node-red-contrib-cron
    - node-red

