- name: install apt packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - curl
    - build-essential


#sudo apt-get update
#$ curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -
#$ apt-get install nodejs

#- name: install ARMHF-compatible nodejs
#  apt: deb=http://node-arm.herokuapp.com/node_latest_armhf.deb

- name: install node-RED
  npm: name="{{ item }}" global=yes state=present
  with_items:
    - nodejs

- name: install node-RED
  npm: name="{{ item }}" global=yes state=present
  with_items:
    - node-red-contrib-cron
    - node-red

